### ISSUE TITLE
Stealing cookie?

### ISSUE THREAD

**Issue by romses** [k3a/yourls-ldap-plugin#4]
I installed the Plugin in yourls 1.7 and cannot login.
After entering my credentials, i got a blanc page displaying

Stealing cookie?

**Comment by siasmj** [comment]
Hi there. I too am having this problem. I tried revising things per https://code.google.com/p/yourls/issues/detail?id=1229 but that did not seem to solve the issue either.

**Comment by davoaust** [comment]
This is caused by the user being allowed via LDAP but not existing as a YourLS user. When YourLS looks up the cookie it can't find the user and then throws that error.

I've just created a pull request for updated functionality that will add LDAP users that aren't in config.php. It works well with my prior update to provide group based auth.
